export const showcaseProjects = [
  {
    id: "p1",
    title: "AI Resume Analyzer",
    shortDescription: "An ATS-friendly resume scanner that uses LLMs to provide actionable feedback for tier-3 college students.",
    bannerUrl: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=800&q=80",
    techStack: ["React", "FastAPI", "OpenAI", "PostgreSQL"],
    domain: "AI", // AI, Web Development, Cyber Security, etc.
    difficulty: "Advanced", // Beginner, Intermediate, Advanced
    status: "Recruiting", // Recruiting, In Progress, Completed
    category: "Featured Projects", // Featured, Startup, Hackathon, Open Source, etc.
    mentor: { name: "Rahul Sharma", role: "IIT Delhi Alumni", avatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=150" },
    organization: "Topper Mantra Labs",
    teamSize: { current: 6, max: 10 },
    openRoles: ["Frontend Developer", "AI Engineer", "UI/UX Designer"],
    progress: 78, // percentage
    estimatedCompletion: "Nov 2026",
    metrics: { stars: 245, views: 1200, bookmarks: 89 },
    overview: "Tier-3 college students often face immediate rejection by Applicant Tracking Systems (ATS) because they don't know how to format their resumes or use the right keywords. We are building an open-source tool that simulates a FAANG ATS and provides direct, actionable feedback powered by OpenAI.",
    problemStatement: "Over 80% of student resumes are rejected before human review. Existing tools are expensive or generic. We need a free, highly specialized tool for tech roles.",
    github: "github.com/toppermantra/ai-resume",
    tasks: [
      { id: "t1", title: "Setup FastAPI backend", status: "Completed", assignee: "Rahul S." },
      { id: "t2", title: "Integrate OpenAI structured outputs", status: "In Progress", assignee: "Priya D." },
      { id: "t3", title: "Design Landing Page", status: "To Do", assignee: "Unassigned" },
    ],
    members: [
      { name: "Priya Das", role: "Backend Lead", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150" },
      { name: "Karan Singh", role: "Fullstack", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150" },
    ]
  },
  {
    id: "p2",
    title: "OpenCampus Decentralized Voting",
    shortDescription: "A blockchain-based secure voting system for university student council elections.",
    bannerUrl: "https://images.unsplash.com/photo-1622630998477-20aa696ecb05?auto=format&fit=crop&w=800&q=80",
    techStack: ["Solidity", "Next.js", "Ethers.js", "Tailwind"],
    domain: "Blockchain",
    difficulty: "Intermediate",
    status: "In Progress",
    category: "Hackathon Projects",
    mentor: { name: "Neha Kapoor", role: "Web3 Researcher", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150" },
    organization: "ETHIndia Build",
    teamSize: { current: 4, max: 4 },
    openRoles: [],
    progress: 95,
    estimatedCompletion: "Oct 2026",
    metrics: { stars: 120, views: 500, bookmarks: 34 },
    overview: "College elections are often plagued by inefficiencies and lack of transparency. OpenCampus uses smart contracts to ensure 100% transparent and immutable voting records.",
    problemStatement: "Provide a trustless system for student elections.",
    github: "github.com/opencampus/voting",
    tasks: [],
    members: []
  },
  {
    id: "p3",
    title: "EcoTrack Mobile App",
    shortDescription: "React Native app that helps users track their carbon footprint through gamification.",
    bannerUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80",
    techStack: ["React Native", "Firebase", "Node.js"],
    domain: "App Development",
    difficulty: "Beginner",
    status: "Recruiting",
    category: "Open Source",
    mentor: { name: "Arjun Reddy", role: "Startup Founder", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150" },
    organization: "GreenTech Open Source",
    teamSize: { current: 2, max: 5 },
    openRoles: ["Mobile Developer", "QA Tester"],
    progress: 15,
    estimatedCompletion: "Jan 2027",
    metrics: { stars: 89, views: 300, bookmarks: 12 },
    overview: "Making climate action fun and engaging through daily challenges, leaderboards, and real-world rewards.",
    problemStatement: "Climate apps are boring. We need gamification to drive habit changes.",
    github: "github.com/greentech/ecotrack",
    tasks: [],
    members: []
  },
  {
    id: "p4",
    title: "NeuraDesk - AI Customer Support",
    shortDescription: "An intelligent customer support ticket router that classifies and auto-responds to common queries.",
    bannerUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    techStack: ["Python", "FastAPI", "HuggingFace", "React"],
    domain: "Machine Learning",
    difficulty: "Advanced",
    status: "Recruiting",
    category: "Startup Projects",
    mentor: { name: "Sneha Iyer", role: "AI Engineer", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150" },
    organization: "NeuraDesk Startup",
    teamSize: { current: 1, max: 4 },
    openRoles: ["Frontend Dev", "DevOps"],
    progress: 30,
    estimatedCompletion: "Dec 2026",
    metrics: { stars: 156, views: 800, bookmarks: 45 },
    overview: "Small businesses struggle to manage customer support tickets. NeuraDesk uses fine-tuned LLMs to automatically categorize tickets and draft responses, saving up to 60% of agent time.",
    problemStatement: "High volume of repetitive support queries overwhelms small teams.",
    github: "github.com/neuradesk/core",
    tasks: [],
    members: []
  },
  {
    id: "p5",
    title: "CryptoWallet UI Kit",
    shortDescription: "A comprehensive open-source UI kit for Web3 applications built with React and Tailwind.",
    bannerUrl: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=800&q=80",
    techStack: ["React", "TailwindCSS", "Figma", "Storybook"],
    domain: "Design",
    difficulty: "Beginner",
    status: "In Progress",
    category: "Open Source",
    mentor: { name: "Rahul Sharma", role: "Frontend Lead", avatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=150" },
    organization: "Web3 Designers",
    teamSize: { current: 3, max: 5 },
    openRoles: ["UI Designer", "Technical Writer"],
    progress: 60,
    estimatedCompletion: "Aug 2026",
    metrics: { stars: 890, views: 2500, bookmarks: 120 },
    overview: "Building Web3 apps is hard enough. Developers shouldn't have to rebuild wallet connection modals and token swap interfaces from scratch. This library provides highly customizable, accessible components.",
    problemStatement: "Lack of standardized, accessible UI components in Web3.",
    github: "github.com/web3designers/ui-kit",
    tasks: [],
    members: []
  },
  {
    id: "p6",
    title: "Campus Marketplace",
    shortDescription: "A platform for college students to buy and sell used books, electronics, and furniture securely.",
    bannerUrl: "https://images.unsplash.com/photo-1555529771-835f59fc5efe?auto=format&fit=crop&w=800&q=80",
    techStack: ["Next.js", "Supabase", "Prisma", "Stripe"],
    domain: "Web Development",
    difficulty: "Intermediate",
    status: "Completed",
    category: "Featured Projects",
    mentor: { name: "Arjun Reddy", role: "Founder", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150" },
    organization: "CampusConnect",
    teamSize: { current: 4, max: 4 },
    openRoles: [],
    progress: 100,
    estimatedCompletion: "Completed",
    metrics: { stars: 320, views: 4100, bookmarks: 210 },
    overview: "An escrow-based marketplace designed exclusively for students with verified university email addresses, ensuring a safe and scam-free environment.",
    problemStatement: "Students get scammed on Facebook Marketplace and OLX. We need a trusted local ecosystem.",
    github: "github.com/campusconnect/marketplace",
    tasks: [],
    members: []
  }
];

export const projectFilters = {
  domains: ["AI", "Machine Learning", "Web Development", "App Development", "Cyber Security", "Blockchain", "Cloud", "IoT", "Robotics", "Design"],
  difficulties: ["Beginner", "Intermediate", "Advanced"],
  statuses: ["Recruiting", "In Progress", "Completed"],
  categories: ["Featured Projects", "Recruiting Now", "Startup Projects", "Hackathon Projects", "Open Source", "Research Projects", "Industry Projects", "Trending This Week"]
};
